#!/bin/bash
# Download audio from YouTube videos
# Usage: ./scripts/download-youtube.sh

OUTPUT_DIR="$HOME/Desktop/gravacoes-youtube"
LOG_FILE="$OUTPUT_DIR/_resultado.txt"
FAILED_FILE="$OUTPUT_DIR/_falhas.txt"

mkdir -p "$OUTPUT_DIR"
> "$LOG_FILE"
> "$FAILED_FILE"

URLS=(
  "https://youtu.be/knAtDUn4dWU"
  "https://youtu.be/pHVT2Pf0ba8"
  "https://youtu.be/6tMOvmwuDco"
  "https://youtu.be/KcK0wne01ek"
  "https://youtu.be/zgO65QtLCpw"
  "https://youtu.be/CLOJVoc19tc"
  "https://www.youtube.com/watch?v=PF27MFfCxws"
  "https://youtu.be/BoNJ-UeVtVw"
  "https://youtu.be/mEEqeMomufk"
  "https://www.youtube.com/watch?v=GdmjRbBpMKU"
  "https://www.youtube.com/watch?v=SccCdhPvpAw"
  "https://youtu.be/kxe8Jo6PQ48"
  "https://www.youtube.com/watch?v=XJno2k9vqis"
  "https://youtu.be/KdukqsU5qm4"
  "https://youtu.be/wggs7Ht42hw"
  "https://youtu.be/ua4kJPGSSIU"
  "https://youtu.be/3jX6fb8q6kU"
  "https://www.youtube.com/watch?v=hFTcrbLtECo"
  "https://youtu.be/Sketsv0ngU0"
  "https://www.youtube.com/watch?v=h2oyPR-2P_c"
  "https://youtu.be/d2bzySxa48o"
  "https://youtu.be/ggBYb1fh2KE"
  "https://www.youtube.com/watch?v=BbM0py6ZggM"
  "https://youtu.be/RlrDQbS11Yg"
  "https://www.youtube.com/watch?v=wMBVCg6KPdw"
  "https://youtu.be/JoRLiPeVrRE"
  "https://youtu.be/plAgYvpaCgw"
  "https://youtu.be/Y1OQxkDMFKw"
  "https://youtu.be/FZQeWkjmw8w"
  "https://youtu.be/ibPcuAxQZaQ"
  "https://www.youtube.com/watch?v=ofgHDGhhI7w"
  "https://www.youtube.com/watch?v=U-UwbZSS4AQ"
  "https://www.youtube.com/watch?v=wUbaG0p_pZw"
  "https://www.youtube.com/watch?v=hpYh-b-PJ6k"
  "https://youtu.be/iiVhhrVcGBU"
  "https://youtu.be/ZrF9Eeiae2c"
  "https://www.youtube.com/watch?v=CkjUS8WoTWo"
  "https://www.youtube.com/watch?v=ZBNFPvyBDus"
  "https://www.youtube.com/watch?v=ZlN_EbhYkYE"
  "https://youtu.be/Q81Z1ZEYL68"
  "https://www.youtube.com/watch?v=ZgJKoNWU9Tg"
  "https://youtu.be/pqVJIuZmp5s"
  "https://youtu.be/R9k0b_wsuOg"
  "https://youtu.be/ZzkQ-3zRMUs"
  "https://www.youtube.com/watch?v=ax9uqIaqMoA"
  "https://www.youtube.com/watch?v=GGW3_A7JpSE"
  "https://www.youtube.com/watch?v=_6nZdXX63TI"
  "https://www.youtube.com/watch?v=aWpEcZfBadA"
  "https://youtu.be/LwYL5WxQPOk"
  "https://www.youtube.com/watch?v=K0v4Kw_Ygq0"
  "https://www.youtube.com/watch?v=fifgmyzCehc"
  "https://www.youtube.com/watch?v=fwiQtU1-mmk"
  "https://www.youtube.com/watch?v=Ua2qLHUhC2I"
  "https://www.youtube.com/watch?v=AyjS5rVqkWI"
  "https://youtu.be/38opfyBnpNw"
  "https://youtu.be/iCIcFPNi-U0"
  "https://youtu.be/zqSmukJOtsU"
  "https://youtu.be/ZkIRBztA0_I"
  "https://www.youtube.com/watch?v=uRhxPv5T25s"
  "https://www.youtube.com/watch?v=jjjQ9ym99dY"
  "https://youtu.be/kbkxLHzlRMw"
  "https://youtu.be/CC6X57xCTdE"
  "https://youtu.be/Hb6bXt7Icu4"
  "https://www.youtube.com/watch?v=PfsK-EVdYNU"
  "https://youtu.be/jzlahO4sqqQ"
  "https://youtu.be/nl4slU5ApO8"
  "https://youtu.be/2QhzD7vM1LQ"
  "https://youtu.be/NOxV-kix3bI"
  "https://youtu.be/FutjZFocXFk"
  "https://youtu.be/iTGyl0vnVVk"
  "https://youtu.be/xONqY9zbxo4"
  "https://youtu.be/FUmAZQ_jBiI"
  "https://youtu.be/EzaCRHAvUVk"
  "https://youtu.be/ZsVJQ7rqDLE"
  "https://youtu.be/pfNHfn1ObeY"
  "https://youtu.be/j8lmtpLMxh0"
  "https://youtu.be/j8qjhQKBOM4"
  "https://youtu.be/ucS1jdeO6L4"
  "https://youtu.be/aNVNykXG02k"
  "https://youtu.be/kad8cF-Eh2I"
  "https://youtu.be/61-zYYbiCE8w"
  "https://youtu.be/CVs9nHDx3W4"
  "https://youtu.be/UNRsbFB2XDM"
  "https://youtu.be/ncFvLHrc6ik"
  "https://youtu.be/DSAyLgkzeOQ"
  "https://youtu.be/dgUdaEZjg0M"
  "https://youtu.be/b5_CI5VngNs"
  "https://youtu.be/mSlcesqZxtY"
  "https://youtu.be/o4dB-vyNKAY"
  "https://youtu.be/bZngMVDmiOw"
  "https://youtu.be/Rn_nT5-vTWw"
  "https://youtu.be/mGz1fkmtWq8"
  "https://www.youtube.com/watch?v=TX-pz0vxYc4"
  "https://youtu.be/hxf7kKl2pTY"
  "https://youtu.be/yeZ5hmZRVws"
  "https://youtu.be/DKHQ1mZ9iy8"
  "https://www.youtube.com/watch?v=TXpRaSN2GhU"
  "https://youtu.be/NLhJLbEQWhE"
  "https://youtu.be/mCQWVoT07BA"
  "https://youtu.be/g0bWyoIjjYk"
  "https://www.youtube.com/watch?v=4SmCBLORMAI"
  "https://www.youtube.com/watch?v=7sMto3w6Cys"
  "https://youtu.be/YilOV02AOJQ"
  "https://youtu.be/2NiEC1mD7po"
  "https://youtu.be/fstE_t1oBJk"
  "https://youtu.be/hsAKOpb1QjE"
  "https://youtu.be/weUue_8FuBI"
  "https://youtu.be/kGZEprtgCFU"
  "https://youtu.be/Pd_qxHfJXmw"
  "https://youtu.be/8oT4FQ7LIic"
  "https://youtu.be/jNkrYCccby8"
  "https://youtu.be/323SqrdOtcY"
  "https://youtu.be/cpV-D2RAVFQ"
  "https://youtu.be/UDUEudKsOrk"
  "https://youtu.be/Wa1vDrMLoCE"
  "https://youtu.be/jFDktuAVopg"
  "https://youtu.be/BdGmsjYPpR0"
  "https://youtu.be/PyUSVVHkzzE"
)

TOTAL=${#URLS[@]}
OK=0
FAIL=0

echo "=== Download de $TOTAL videos do YouTube ==="
echo "Destino: $OUTPUT_DIR"
echo ""

for i in "${!URLS[@]}"; do
  NUM=$((i + 1))
  URL="${URLS[$i]}"
  echo "[$NUM/$TOTAL] $URL"

  if yt-dlp -x --audio-format mp3 \
    -o "$OUTPUT_DIR/%(upload_date>%Y-%m-%d)s - %(title)s.%(ext)s" \
    --no-overwrites \
    "$URL" 2>&1; then
    echo "OK: $URL" >> "$LOG_FILE"
    OK=$((OK + 1))
    echo "  -> OK"
  else
    echo "FALHA: $URL" >> "$LOG_FILE"
    echo "$URL" >> "$FAILED_FILE"
    FAIL=$((FAIL + 1))
    echo "  -> FALHA"
  fi
  echo ""
done

echo "================================"
echo "RESULTADO: $OK OK / $FAIL falhas (de $TOTAL)"
echo "Arquivos em: $OUTPUT_DIR"
echo "Log completo: $LOG_FILE"

if [ "$FAIL" -gt 0 ]; then
  echo ""
  echo "URLs que falharam (salvas em $FAILED_FILE):"
  cat "$FAILED_FILE"
  echo ""
  echo "Para tentar novamente apenas as falhas:"
  echo "  cat '$FAILED_FILE' | xargs -I{} yt-dlp -x --audio-format mp3 -o '$OUTPUT_DIR/%(upload_date>%Y-%m-%d)s - %(title)s.%(ext)s' '{}'"
fi
